### ISSUE TITLE
canOpenURL: failed for URL

### ISSUE THREAD

**Issue by davorpeic** [EddyVerbruggen/nativescript-appavailability#2]
Hi Eddy,

I'm getting console log errors when the app is not available, the module returns `false`, and from that point of view I don't see any errors in functionality. My guess is that the native method is rejecting the "check" when the app doesn't exist.

NS 2.5, Angular + TS
IOS 10.2 Simulator
```
-canOpenURL: failed for URL: "googlemaps://" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
``` 

In case when the app exists, there is no error.
Thanks

**Comment by EddyVerbruggen** [comment]
Yeah that message is a bit unfortunate. It's all over the internet as well. It's iOS doing that, nothing I can do to suppress it really.
